Repository qiniu/java-sdk, pull requests merged in 2020-09, with the labels that each got.

#495 update qiniu exception
  src/main/java/com/qiniu/common/QiniuException.java
Labels: size/XS

#496 add request method.
  src/main/java/com/qiniu/http/Response.java
Labels: size/S

#479 [qvs]add stopStream and delete check argument
  src/main/java/com/qiniu/qvs/DeviceManager.java
  src/main/java/com/qiniu/qvs/NameSpaceManager.java
  src/main/java/com/qiniu/qvs/README.md
  src/main/java/com/qiniu/qvs/StreamManager.java
  src/main/java/com/qiniu/qvs/model/Device.java
  src/main/java/com/qiniu/qvs/model/NameSpace.java
  src/main/java/com/qiniu/qvs/model/StaticLiveRoute.java
  src/test/java/test/com/qiniu/qvs/DeviceManagerTest.java
Labels: size/XL

#497 update qvs readme[ci skip]
  src/main/java/com/qiniu/qvs/README.md
Labels: size/S
