Repository qiniu/java-sdk, pull requests merged in 2020-11, with the labels that each got.

#501 LINK-1682 update qvs-java-sdk
  src/main/java/com/qiniu/http/Client.java
  src/main/java/com/qiniu/qvs/DeviceManager.java
  src/main/java/com/qiniu/qvs/NameSpaceManager.java
  src/main/java/com/qiniu/qvs/QvsResponse.java
  src/main/java/com/qiniu/qvs/RecordManager.java
  src/main/java/com/qiniu/qvs/StatsManager.java
  src/main/java/com/qiniu/qvs/StreamManager.java
  src/main/java/com/qiniu/qvs/model/NameSpace.java
  src/main/java/com/qiniu/qvs/model/Template.java
  src/test/java/test/com/qiniu/qvs/DeviceManagerTest.java
  src/test/java/test/com/qiniu/qvs/RecordTest.java
  src/test/java/test/com/qiniu/qvs/StatsTest.java
  src/test/java/test/com/qiniu/qvs/StreamTest.java
Labels: size/L

#499 Add remote ip
  src/main/java/com/qiniu/http/Client.java
  src/test/java/test/com/qiniu/HttpTest.java
  src/test/java/test/com/qiniu/storage/BucketTest2.java
Labels: size/L

#500 check prefop id by GET
  src/main/java/com/qiniu/processing/OperationManager.java
  src/test/java/test/com/qiniu/processing/PfopTest.java
  src/test/java/test/com/qiniu/storage/FormUploadTest.java
Labels: size/M

#504 LINK-1702 PTZ qvs-java-sdk
  src/main/java/com/qiniu/qvs/PTZManager.java
  src/test/java/test/com/qiniu/qvs/PTZTest.java
Labels: size/L

#503 LINK-1682 update qvs-java-sdk
  src/main/java/com/qiniu/http/Client.java
  src/main/java/com/qiniu/qvs/DeviceManager.java
  src/main/java/com/qiniu/qvs/NameSpaceManager.java
  src/main/java/com/qiniu/qvs/PTZManager.java
  src/main/java/com/qiniu/qvs/QvsResponse.java
  src/main/java/com/qiniu/qvs/RecordManager.java
  src/main/java/com/qiniu/qvs/StatsManager.java
  src/main/java/com/qiniu/qvs/StreamManager.java
  src/main/java/com/qiniu/qvs/model/NameSpace.java
  src/main/java/com/qiniu/qvs/model/Template.java
  src/test/java/test/com/qiniu/qvs/DeviceManagerTest.java
  src/test/java/test/com/qiniu/qvs/PTZTest.java
  src/test/java/test/com/qiniu/qvs/RecordTest.java
  src/test/java/test/com/qiniu/qvs/StatsTest.java
  src/test/java/test/com/qiniu/qvs/StreamTest.java
Labels: size/XL
