Repository qiniu/java-sdk, pull requests merged in 2021-04, with the labels that each got.

#510 refactor resume upload to support v1 and v2 from ys_dev
  .github/workflows/ci-test.yml
  src/main/java/com/qiniu/common/QiniuException.java
  src/main/java/com/qiniu/http/Response.java
  src/main/java/com/qiniu/storage/ConcurrentResumeUploader.java
  src/main/java/com/qiniu/storage/Configuration.java
  src/main/java/com/qiniu/storage/FixBlockUploader.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformer.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformerV1.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformerV2.java
  src/main/java/com/qiniu/storage/ResumeUploadSource.java
  src/main/java/com/qiniu/storage/ResumeUploadSourceFile.java
  src/main/java/com/qiniu/storage/ResumeUploadSourceStream.java
  src/main/java/com/qiniu/storage/ResumeUploader.java
  src/main/java/com/qiniu/storage/UploadManager.java
  src/main/java/com/qiniu/storage/UploadOptions.java
  src/main/java/com/qiniu/storage/UploadToken.java
  src/main/java/com/qiniu/storage/model/FileInfo.java
  src/test/java/test/com/qiniu/TestConfig.java
  src/test/java/test/com/qiniu/storage/BucketTest.java
  src/test/java/test/com/qiniu/storage/RecordUploadTest.java
  src/test/java/test/com/qiniu/storage/ResumeUploadTest.java
Labels: size/XXL

#512 add api layer from ys_dev
  examples/upload_v1_api.java
  examples/upload_v2_api.java
  src/main/java/com/qiniu/http/Client.java
  src/main/java/com/qiniu/storage/Api.java
  src/main/java/com/qiniu/storage/ApiQueryRegion.java
  src/main/java/com/qiniu/storage/ApiUpload.java
  src/main/java/com/qiniu/storage/ApiUploadV1MakeBlock.java
  src/main/java/com/qiniu/storage/ApiUploadV1MakeFile.java
  src/main/java/com/qiniu/storage/ApiUploadV1PutChunk.java
  src/main/java/com/qiniu/storage/ApiUploadV2AbortUpload.java
  src/main/java/com/qiniu/storage/ApiUploadV2CompleteUpload.java
  src/main/java/com/qiniu/storage/ApiUploadV2InitUpload.java
  src/main/java/com/qiniu/storage/ApiUploadV2ListParts.java
  src/main/java/com/qiniu/storage/ApiUploadV2UploadPart.java
  src/main/java/com/qiniu/storage/ApiUtils.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformer.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformerV1.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformerV2.java
  src/main/java/com/qiniu/storage/ResumeUploadSourceFile.java
  src/test/java/test/com/qiniu/storage/ApiQueryRegionTest.java
  src/test/java/test/com/qiniu/storage/ApiUploadV1Test.java
  src/test/java/test/com/qiniu/storage/ApiUploadV2Test.java
Labels: size/XXL

#515 version to 7.5.0 from ys_dev
  CHANGELOG.md
  README.md
  src/main/java/com/qiniu/common/Constants.java
Labels: size/S

#519 ASLAN-6794 add codecov
  .github/workflows/ci-test.yml
Labels: size/S

#518 支持构建 Download url & 基础 api 支持流姿势上传
  CHANGELOG.md
  src/main/java/com/qiniu/common/Constants.java
  src/main/java/com/qiniu/http/Client.java
  src/main/java/com/qiniu/http/RequestStreamBody.java
  src/main/java/com/qiniu/http/Response.java
  src/main/java/com/qiniu/processing/OperationManager.java
  src/main/java/com/qiniu/storage/Api.java
  src/main/java/com/qiniu/storage/ApiUploadV1MakeBlock.java
  src/main/java/com/qiniu/storage/ApiUploadV1PutChunk.java
  src/main/java/com/qiniu/storage/ApiUploadV2UploadPart.java
  src/main/java/com/qiniu/storage/BucketManager.java
  src/main/java/com/qiniu/storage/DownloadPrivateCloudUrl.java
  src/main/java/com/qiniu/storage/DownloadUrl.java
  src/main/java/com/qiniu/util/Md5.java
  src/test/java/test/com/qiniu/HttpTest.java
  src/test/java/test/com/qiniu/TestConfig.java
  src/test/java/test/com/qiniu/storage/ApiUploadV1Test.java
  src/test/java/test/com/qiniu/storage/ApiUploadV2Test.java
  src/test/java/test/com/qiniu/storage/DownloadUrlTest.java
  src/test/java/test/com/qiniu/storage/ZoneTest.java
Labels: size/XL

#520 change version to 7.6.0
  CHANGELOG.md
  README.md
  src/main/java/com/qiniu/common/Constants.java
Labels: size/XS
