Repository qiniu/java-sdk, pull requests merged in 2022-10, with the labels that each got.

#563 fix the failed test case `StreamingTest`
  src/test/java/test/com/qiniu/streaming/StreamingTest.java
Labels: size/S

#562 qvs LINK-2695 add controlGBRecord
  src/main/java/com/qiniu/qvs/DeviceManager.java
  src/main/java/com/qiniu/qvs/QvsMap.java
  src/main/java/com/qiniu/qvs/model/PlayContral.java
  src/main/java/com/qiniu/qvs/model/VoiceChat.java
  src/test/java/test/com/qiniu/qvs/DeviceManagerTest.java
Labels: size/L

#557 add region:ap-northeast-1
  src/main/java/com/qiniu/common/Zone.java
  src/main/java/com/qiniu/storage/BucketManager.java
  src/main/java/com/qiniu/storage/Region.java
  src/test/java/test/com/qiniu/TestConfig.java
  src/test/java/test/com/qiniu/storage/BucketTest.java
Labels: size/L, needs-ok-to-test

#559 QRTC-1984 rtc v3 update app bug fix
  src/main/java/com/qiniu/rtc/model/AppParam.java
  src/main/java/com/qiniu/rtc/service/AppService.java
  src/test/java/test/com/qiniu/rtc/RtcTest.java
Labels: size/XS, needs-ok-to-test

#561 Resume check ctx expire
  CHANGELOG.md
  README.md
  src/main/java/com/qiniu/common/Constants.java
  src/main/java/com/qiniu/http/Response.java
  src/main/java/com/qiniu/storage/BaseUploader.java
  src/main/java/com/qiniu/storage/FormUploader.java
  src/main/java/com/qiniu/storage/ResumeUploadPerformerV1.java
  src/main/java/com/qiniu/storage/ResumeUploadSource.java
  src/main/java/com/qiniu/storage/ResumeUploadSourceFile.java
  src/main/java/com/qiniu/storage/ResumeUploader.java
  src/main/java/com/qiniu/storage/Retry.java
Labels: size/L, needs-ok-to-test
