Repository qiniu/java-sdk, pull requests merged in 2022-03, with the labels that each got.

#542 Optimize credential
  src/main/java/com/qiniu/processing/OperationManager.java
  src/main/java/com/qiniu/storage/BucketManager.java
  src/main/java/com/qiniu/util/Auth.java
  src/test/java/test/com/qiniu/storage/BucketTest.java
  src/test/java/test/com/qiniu/util/AuthTest.java
Labels: size/L, needs-ok-to-test

#545 fix file source read memory overflow
  CHANGELOG.md
  src/main/java/com/qiniu/common/Constants.java
  src/main/java/com/qiniu/storage/ResumeUploadSourceFile.java
Labels: size/S, needs-ok-to-test

#547 QRTC-1825 服务端支持全量覆盖，合流支持z参数, strechMode使用枚举
  src/main/java/com/qiniu/rtc/model/CallbackParam.java
  src/main/java/com/qiniu/rtc/model/MergeTrackParam.java
  src/main/java/com/qiniu/rtc/model/StretchModeEnum.java
  src/main/java/com/qiniu/rtc/model/WatermarksParam.java
  src/main/java/com/qiniu/rtc/service/CallbackService.java
  src/main/java/com/qiniu/rtc/service/RoomService.java
Labels: size/M, needs-ok-to-test
