Repository qiniu/java-sdk, pull requests merged in 2023-05, with the labels that each got.

#576 解决 URLEncoder 空格为 + 号问题
  src/main/java/com/qiniu/cdn/CdnManager.java
  src/test/java/test/com/qiniu/cdn/CdnManagerTest.java
Labels: size/M, ok-to-test

#579 deprecated listV2
  src/main/java/com/qiniu/storage/BucketManager.java
Labels: size/S, needs-ok-to-test

#572 Change Api host
  src/main/java/com/qiniu/storage/BucketManager.java
Labels: size/S, needs-ok-to-test

#580 LINK-2757 qvs add playExpireSec
  src/main/java/com/qiniu/qvs/StreamManager.java
  src/main/java/com/qiniu/qvs/model/DynamicLiveRoute.java
  src/main/java/com/qiniu/qvs/model/StaticLiveRoute.java
Labels: size/M
